### ISSUE TITLE
MASA Blazor 0.4.0 roadmap

### ISSUE THREAD

**Issue by xie1wei2** [BlazorComponent/MASA.Blazor#406]
Here are some of the new content and features in 0.4.0, as well as some historical bug fixes.
这里是0.4.0中新增的内容与功能，以及修复历史中存在的一些bug。 

We are committed to maintaining the history of MASA Blazor on a regular basis, as well as collecting external input to improve the features of MASA Blazor and problems in use. Thank you for your continued attention and valuable comments.
The following is the content of the 0.4.0 plan, and some functions have been realized

我们一直致力于定期维护历史内容，以及收集采纳各方外部的意见不断完善MASA Blazor的相关特性以及在使用中出现的问题，非常感谢各位一直以来的关注和宝贵的意见。 
以下为本次0.4.0计划内容，部分功能已经实现 

The new content
* [x]  【Doc】Rich text editor（富文本编辑器）
An important component of text editing
文本编辑的重要组件

* [x] 【Error】Interface exception capture（全局异常捕获）
Improve the web page exception acquisition and prompt
完善网页异常的获取与提示

* [x] 【Captcha】Captcha component（验证码组件）
Common login authentication components
常用的登录验证组件

* [ ] 【Loader Container】The container to load the animation（加载动画的容器组件）

* [ ] 【Carousel】Play and switch components（轮播组件）

* [x] 【Divider】Divisible content（内容分割线）

* [ ] 【Form】Verification and positioning（验证定位组件）

* [x] 【TextField】Supported Number Types（支持数字类型）

* [x] 【Toast】Message prompt box（消息提示框）

* [ ] 【Autocomplete】
