### ISSUE TITLE
[Task] MASA Blazor 0.5.0 Release To-do list

### ISSUE THREAD

**Issue by capdiem** [BlazorComponent/MASA.Blazor#539]
# 0.5.0 Release To-do list

The following is an to-do list of tasks after we release the 0.5.0.

## Update the **Masa.Template** 
- [x] Upgrade the package version of **Masa.Blazor** to 0.5.0. @MayueCif 
- [x] Use `masa-blazor.min.css` instead of `masa-blazor.css`  and `masa-extend-blazor.css`. @MayueCif 

## Update [MASA.Blazor.Pro](https://github.com/BlazorComponent/MASA.Blazor.Pro)
- [x] Upgrade the package version of **Masa.Blazor** to 0.5.0. @MayueCif 
  - https://github.com/BlazorComponent/MASA.Blazor.Pro/pull/146
- [x] Use `masa-blazor.min.css` instead of `masa-blazor.css`  and `masa-extend-blazor.css`. @MayueCif 
  - https://github.com/BlazorComponent/MASA.Blazor.Pro/pull/152

**Comment by doddgu** [comment]
@MayueCif PTAL
